---
services:
  centroiding:
    build: "."
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 8G
    healthcheck:
      test: ["NONE"]
      interval: 200s
      timeout: 200s
      retries: 5
    image: adafede/centroidr
    networks:
      - service-service-frontend
    security_opt:
      - apparmor:unconfined
      - no-new-privileges:true
    user: centroid-user
    volumes:
      - "./data:/home/centroid-user/"
    command: >
      Rscript centroiding.R
      ${INPUT_FILE}
      ${PATTERN}
      ${REPLACEMENT}

networks:
  service-service-frontend:
